name: ADL_HW2
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - bitsandbytes==0.44.1
      - datasets==3.0.1
      - gdown
      - peft==0.13.0
      - torch==2.4.1
      - transformers>=4.51.0
      # - torch==2.1.0
      # - scikit-learn==1.5.1
      # - nltk==3.9.1
      # - tqdm
      # - numpy==1.26.4
      # - pandas
      # - transformers==4.50.0
      # - datasets==2.21.0
      # - accelerate==0.34.2
      # - evaluate
      # - matplotlib
      - gdown
# Usage:
# conda env create -f environment.yml
# conda activate ADL_HW2