name: ADL_HW2
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - bitsandbytes==0.44.1
      - datasets==3.0.1
      - evaluate==0.4.0
      - gdown
      - matplotlib
      - peft==0.13.0
      - torch==2.4.1
      - transformers>=4.51.0
# Usage:
# conda env create -f environment.yml
# conda activate ADL_HW2